INSERT INTO position
    (name,code) values
    ('Other*','OTHER'),
    ('Field Manager','FIELD_MANAGER');

UPDATE employee
SET position_id = null
WHERE position_id in (SELECT id FROM position WHERE code NOT IN ('OWNER','DIRECTOR_OF_OPERATIONS','REGIONAL_FIELD_DIRECTOR',
'FIELD_DIRECTOR','CANVASSER', 'OTHER','FIELD_MANAGER'));

DELETE FROM position WHERE code NOT IN ('OWNER','DIRECTOR_OF_OPERATIONS','REGIONAL_FIELD_DIRECTOR','FIELD_DIRECTOR',
'CANVASSER', 'OTHER','FIELD_MANAGER');
